<a href="https://colab.research.google.com/github/nguyenngoctruong2k1/CS114.L22.KHCL/blob/main/ML_Colab_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import dữ liệu

In [1]:
import pandas as pd
train = pd.read_csv("https://cs.uit.edu.vn/data2.txt",header=None)
test = pd.read_csv("https://cs.uit.edu.vn/data3.txt",header=None)
train

0         1
0      6083695  0.521842
1      1954367  0.152648
2      3734185  0.298548
3      5839301  0.460480
4      6343427  0.527977
...        ...       ...
71110  4472112  0.350379
71111  5471895  0.429955
71112  9837364  0.801394
71113  9466593  0.776407
71114  4080801  0.314468

[71115 rows x 2 columns]

In [2]:
train[1]

0        0.521842
1        0.152648
2        0.298548
3        0.460480
4        0.527977
           ...   
71110    0.350379
71111    0.429955
71112    0.801394
71113    0.776407
71114    0.314468
Name: 1, Length: 71115, dtype: float64

In [3]:
import numpy as np

X_train = np.array(train[0])
y_train = np.array(train[1])
X_test = np.array(test[0])
y_test = np.array(test[1])
X_train

array([6083695, 1954367, 3734185, ..., 9837364, 9466593, 4080801])

In [5]:
import numpy as np
import sklearn
from sklearn.linear_model import LinearRegression

In [7]:
def increaseDimension(X_):
  X = X_
  X = np.hstack((X, np.log2(X_)))
  X = np.hstack((X, X_*np.log2(X_)))
  X = np.hstack((X, X_*X_))
  return X

In [8]:
X_train = increaseDimension(X_train)
X_test = increaseDimension(X_test)
X_train

array([6.08369500e+06, 1.95436700e+06, 3.73418500e+06, ...,
       9.67737305e+13, 8.96163830e+13, 1.66529368e+13])

# y = a*x + b* x^2 + c * lg(x) + d *x *lg(x) + e

In [ ]:
import math

In [11]:
X_train = np.reshape(X_train,(-1,4))
X_test = np.reshape(X_test,(-1,4))
X_train

array([[6.08369500e+06, 1.95436700e+06, 3.73418500e+06, 5.83930100e+06],
       [6.34342700e+06, 1.35557400e+06, 7.25488000e+05, 1.19188700e+06],
       [4.55629200e+06, 9.98959600e+06, 7.69804000e+06, 1.69081600e+06],
       ...,
       [2.50807852e+13, 5.24152977e+13, 3.44011576e+13, 7.65941783e+13],
       [6.61523544e+10, 4.80423375e+13, 2.75331078e+13, 1.99997857e+13],
       [2.99416349e+13, 9.67737305e+13, 8.96163830e+13, 1.66529368e+13]])

In [12]:
X_train.shape

(71115, 4)

In [13]:
y_train

array([0.521842, 0.152648, 0.298548, ..., 0.801394, 0.776407, 0.314468])

# dựng mode

In [14]:
from sklearn.linear_model import LinearRegression
mode = LinearRegression()

In [15]:
mode.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
X_train

In [16]:
y_predit = mode.predict(X_test)

In [17]:
y_predit

array([0.40667401, 0.40667401, 0.40667401, ..., 0.37686147, 0.44220664,
       0.4592006 ])

In [18]:
y_test

array([4.12166, 3.92089, 3.2154 , ..., 2.90918, 1.80292, 1.82795])

In [19]:
np.average(y_test)

2.642811968838527

In [20]:
np.average((y_predit - y_test)**2)

5.277590215023011